on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy to cloudflare worker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        name: Deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            LINE_NOTIFY_TOKEN
            CF_ACCESS_CLIENT_ID
            CF_ACCESS_CLIENT_SECRET
            MAX_API_URL
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
          CF_ACCESS_CLIENT_ID: ${{ vars.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
          MAX_API_URL: ${{ vars.MAX_API_URL }}
